// Code generated by "stringer -type=ErrorType,ErrorLevel,ErrorSeverity -output=const.go"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultType-0]
	_ = x[NotFound-1]
	_ = x[InvalidArguments-2]
	_ = x[InternalError-3]
	_ = x[BadRequest-4]
	_ = x[AccessDenied-5]
	_ = x[Unauthorized-6]
}

const _ErrorType_name = "DefaultTypeNotFoundInvalidArgumentsInternalErrorBadRequestAccessDeniedUnauthorized"

var _ErrorType_index = [...]uint8{0, 11, 19, 35, 48, 58, 70, 82}

func (i ErrorType) String() string {
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultLevel-0]
	_ = x[DataLevel-1]
	_ = x[UseCaseLevel-2]
	_ = x[ContainerLevel-3]
	_ = x[ControllerLevel-4]
	_ = x[TransportLevel-5]
}

const _ErrorLevel_name = "DefaultLevelDataLevelUseCaseLevelContainerLevelControllerLevelTransportLevel"

var _ErrorLevel_index = [...]uint8{0, 12, 21, 33, 47, 62, 76}

func (i ErrorLevel) String() string {
	if i < 0 || i >= ErrorLevel(len(_ErrorLevel_index)-1) {
		return "ErrorLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorLevel_name[_ErrorLevel_index[i]:_ErrorLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultSeverity-0]
	_ = x[Debug-1]
	_ = x[Info-2]
	_ = x[Warning-3]
	_ = x[Critical-4]
	_ = x[Fatal-5]
	_ = x[Panic-6]
}

const _ErrorSeverity_name = "DefaultSeverityDebugInfoWarningCriticalFatalPanic"

var _ErrorSeverity_index = [...]uint8{0, 15, 20, 24, 31, 39, 44, 49}

func (i ErrorSeverity) String() string {
	if i < 0 || i >= ErrorSeverity(len(_ErrorSeverity_index)-1) {
		return "ErrorSeverity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorSeverity_name[_ErrorSeverity_index[i]:_ErrorSeverity_index[i+1]]
}
